### ISSUE TITLE
Compare VIs to their previous versions doesn't work correctly

### ISSUE THREAD

**Issue by sganjoo** [ni/nxg-svn#3]
If the user clicks on a file and selects "SVN -> View History", a list with changes appears. On this list, if the user chooses the option to "Compare With Working Copy" nothing happens. This should have launched the Compare app that ships with LabVIEW NXG.

**Comment by searly** [comment]
https://github.com/ni/nxg-svn/commit/0f4a0c4ae81047e71973c281b0e32072800ca389
